# Generated by Django 2.2.1 on 2019-05-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='url',
        ),
    ]
