# Generated by Django 2.2.1 on 2019-06-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_restaurant_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='company',
            field=models.CharField(choices=[('NA', 'Not available'), ('SDX', 'Sodexo'), ('FZR', 'Fazer')], default='NA', max_length=3),
        ),
    ]
