# Generated by Django 2.2.1 on 2019-06-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190602_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
